### ISSUE TITLE
primary branch naming: main vs master

### ISSUE THREAD

**Issue by ryanj** [conscious-lang/conscious-lang-docs#2]
Is there a bulletproof reason for using `master` as the default / primary branch name in this repo?

Related community terminology issue: https://github.com/kubernetes/website/issues/6525

potential changes:

- [ ] fork `master` (as `main`)
- [ ] use github web ui to change the primary branch to `main`
- [ ] update external links that include outdated references to `master`
- [ ] delete master (wait until external references have been updated to avoid 404s)

Github's advice on this topic: https://github.com/github/renaming

Anticipated impact: it might be just as easy to do this later this year, given upcoming feature updates from GH: https://github.com/github/renaming#later-this-year

**Comment by JHGelpi** [comment]
I would be in favor of changing this as soon as possible, even if there's rework involved.  The very nature of this repo is to address language like this.  We should be at the forefront of this kind of stuff.  That said I don't think I have the necessary permissions to make the updates otherwise I would commit my time to doing so.

**Comment by rbowen** [comment]
I will take care of this ASAP.

**Comment by rbowen** [comment]
Done. Thanks for the nudge.
